# 溫度

In [ ]:
celsius=float(input('請輸入攝氏溫度'))
print(type(celsius))
fahrenheit=(9/5) * celsius + 32
print('華氏溫度',fahrenheit)

# 基本應用

In [2]:
import statistics as st
sample=[5,8,9,6,4,1,2,3,5,6]
print('樣本=',sample)
print('平均數=',st.mean(sample))
print('最大數=',max(sample))
print('最小數=',min(sample))
print('變異數=',round(st.variance(sample),2))
print('標準差=',round(st.stdev(sample),2))

樣本= [5, 8, 9, 6, 4, 1, 2, 3, 5, 6]
平均數= 4.9
最大數= 9
最小數= 1
變異數= 6.32
標準差= 2.51


# if

In [3]:
numA = 3
numB = 4
if numA < numB:
    print('numB是比較大的數')

numB是比較大的數


# 比較大小

In [4]:
numA =int(input('請輸入numA:'))
numB =int(input('請輸入numB:'))
if numA <numB:
    print('numB是比較大的數')
else:
    print('numA是比較大的數')

請輸入numA:1
請輸入numB:2
numB是比較大的數


# For迴圈

In [5]:
sum = 0
for i in range(1, 11):
    sum = sum + i
print('總和:', sum)

總和: 55


# 總和

In [6]:
sample=[2,1,4,8,3,2,6,5,9,7]
sum=0
for i in sample:
    sum=sum+i
print('總和:',sum)

總和: 47


# 印字

In [7]:
mylist='I Iove Avenger IV'
for character in mylist:
    print(character)

I
 
I
o
v
e
 
A
v
e
n
g
e
r
 
I
V


# while迴圈

In [8]:
# 1+2+3+...+10的總和
sum = 0
count = 1
while count <= 10:
    sum = sum +count # sum += count
    count += 1 # count = count +1
print('1+2+3+...+10=',sum)

1+2+3+...+10= 55


# 銀行利息

In [9]:
x = 10000
year = 0
while x < 20000:
    year += 1
    x = x * 1.0104
print(str(year),'年後，存款金額會加倍')

67 年後，存款金額會加倍


# 輸入帳號、密碼

In [10]:
id = 'arron'
pwd = '1234'

while True:
    x = input('請輸入帳號:')
    y = input('請輸入密碼:')
    if(x==id and y==pwd):
        print('歡迎登入')
        break
    else:
        print('帳號/密碼輸入不正確')

請輸入帳號:ARRON
請輸入密碼:1234
帳號/密碼輸入不正確
請輸入帳號:arron
請輸入密碼:1234
歡迎登入


 # C#
    
 # Python

In [11]:
mylist = ['C#','Python','Java','C++']
for i in mylist:
    if i == 'Java':
        continue
    else:
            print(i)

C#
Python
C++


# 取10個亂數

In [12]:
import random
for i in range(0,10):
    print(random.random())

0.920091938167002
0.802316243516092
0.9234048458668487
0.6537275656591783
0.5521691469672474
0.6165025095999718
0.7731160278768996
0.13479705684898868
0.2669319824473314
0.2553137587481533


# 取10個 數字不超過2~8

In [13]:
for i in range(0,10):
    print(random.randint(1,9))

2
3
4
1
6
9
2
4
8
4


# 小遊戲

In [14]:
import random
number=random.randint(1,99)
while True:
    guess=input('請輸入1-99的數字(q離開):')
    if guess == 'q':
        print('離開遊戲')
        break
    else:
        if number==int(guess):
                print('恭喜，答對了')
                break
        else:
                print('答錯了') 

請輸入1-99的數字(q離開):1
答錯了
請輸入1-99的數字(q離開):55
答錯了
請輸入1-99的數字(q離開):q
離開遊戲


# numpy

In [15]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# nump套件ndarray型態，提供element-wise的操作

In [17]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


# ndarrary維度 shape 資料型態

In [18]:
print(type(a_ndarray))
print(a_ndarray.ndim)
print(a_ndarray.shape)
print(a_ndarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


# 六個元素都為0的ID ndarray
# 12個元素都為0的2d ndarray
# 24個元素都未出始化的值
# 10個元素0-9的ID ndarray

In [19]:
z=np.zeros(6)  
print(z)                    
print(np.zeros((2,6)))      
print(np.empty((2,6,2)))    
print(np.arange(10))  

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.24611674e-306]
  [1.29061821e-306 6.23057349e-307]
  [2.22522597e-306 1.06810268e-306]
  [6.23052935e-307 9.34600963e-307]
  [9.34608432e-307 2.22522597e-306]
  [1.33511969e-306 8.34426039e-308]]]
[0 1 2 3 4 5 6 7 8 9]


# ndarray的進階操作

In [20]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# 維ndarray取值

In [21]:
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])  #第二列資料
print(my_2d_array[:,1])  #第二欄資料
print(my_2d_array[1,1])  #第二列第二航資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


# 假設有六個組別"Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"
# 其參加人數分別為56, 8, 19 ,14 ,6 ,71人

In [22]:
groups=["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56, 8, 19 ,14 ,6 ,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


# 用人數去篩選組別

In [23]:
print(ironman_array >=10)
print(groups_array[(ironman_array) >=10])
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarrary轉置

In [24]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


# 有多少數字跟幾行幾列

In [25]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


# ndarray nan(空值)

In [26]:
nan_array=np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# Pandas Data Frame

In [27]:
import pandas as pd

groups  = ["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]
ironmen_dict = {
                "groups": groups,
                "ironmen": ironmen
}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloud       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77

# ironmen各式語法

In [28]:
print(ironmen_df.ndim)
print(ironmen_df.shape)
print(ironmen_df.dtypes)

2
(6, 2)
groups     object
ironmen     int64
dtype: object


# 各種運算

In [29]:
print(ironmen_df.sum())
print(ironmen_df.ironmen.sum())
print(ironmen_df.mean())
print(ironmen_df.median())
print(ironmen_df.describe())

groups     Modern WebDevOpsCloudBig DataSecurity自我挑戰組
ironmen                                           184
dtype: object
184
ironmen    30.666667
dtype: float64
ironmen    16.5
dtype: float64
         ironmen
count   6.000000
mean   30.666667
std    29.803803
min     6.000000
25%    10.250000
50%    16.500000
75%    49.000000
max    77.000000


# 判斷那些組的組名是否為遺失值

In [30]:
import pandas as pd
import numpy as np
groups  = ["Modern Web","DevOps", np.nan, "Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77, np.nan]
ironmen_dict = {
                "groups": groups,
                "ironmen": ironmen
}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.loc[:, "groups"].isnull())     #判斷那些組的組名是遺失值
print(ironmen_df.loc[:, "ironmen"].notnull())   #判斷那些組的組名不是遺失值

0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: groups, dtype: bool
0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: ironmen, dtype: bool


# 刪除空值

In [31]:
a=ironmen_df.dropna()    
a

groups  ironmen
0  Modern Web     59.0
1      DevOps      9.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     77.0

# 空值補0

In [32]:
b=ironmen_df.fillna(0)   
b

groups  ironmen
0  Modern Web     59.0
1      DevOps      9.0
2           0     19.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     77.0
6       自我挑戰組      0.0

# 空值補平均數

In [33]:
c=ironmen_df.ironmen.fillna(ironmen_df.ironmen.mean())  
c

0    59.000000
1     9.000000
2    19.000000
3    14.000000
4     6.000000
5    77.000000
6    30.666667
Name: ironmen, dtype: float64

# 建立 data frame

In [ ]:
import pandas as pd

groups  = ["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
ironmen_df.sort_index()

# 雲端載入

In [34]:
import pandas as pd
ur1="https://storage.googleapis.com/2017_ithome_ironman/data/iris.csv"
iris_df = pd.read_csv(ur1)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
iris_df['Sepal.Length'].median()

5.8

# 自訂一個函數

In [38]:
import math 

def circle(radius):
    area = radius * radius * math.pi
    return area

print(circle(10))

314.1592653589793


# 排序

In [39]:
import random

def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] > a[j]:
                a[i],  a[j]=a[j], a[i] 
    return a


def exchange_sort_r(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range(i+1, len(input_list)):
            if a[i] < a[j]:
                a[i],  a[j]=a[j], a[i] 
    return a

my_vector = random.sample (range(0,100), 10)
print(my_vector)
print(exchange_sort(my_vector))
print(exchange_sort_r(my_vector))

[25, 10, 53, 49, 69, 73, 84, 57, 97, 66]
[10, 25, 49, 53, 57, 66, 69, 73, 84, 97]
[97, 84, 73, 69, 66, 57, 53, 49, 25, 10]


# python的lambda函數

In [40]:
def circle(radius):
    return radius * radius * 3.14

print(circle(10))

314.0


# max

In [41]:
def max(m,n):
    return m if m > n else n
print(max(10,3))

10


# lambda

In [42]:
#lambda
max = lambda m,n: m if m>n else n
print(max(10,3))

10


# lamda寫法

In [43]:
# list *5
a=[1,2,3,4,5]
print(a*5)
#numbpy *5
import numpy as np
b=np.array(a)
print(b*5)
#lamda寫法
c=list(map(lambda x: x*5, a)) #map(function, data)
print(c)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[5, 10, 15, 20, 25]


# 錯誤處理 try:except:

In [44]:
def circle(radius):
    try:
        return radius * radius * 3.14
    except:
        return"請輸入數值"
    
print(circle(10))
print(circle('十'))

314.0
請輸入數值
